### ISSUE TITLE
Double Jump Bug.

### ISSUE THREAD

**Issue by Grewoss** [mx0c/super-mario-python#27]
Walk ontop of an Enemy, this will make you jump, simply press space (jump) to double jump.

![doublejumpbug](https://user-images.githubusercontent.com/25953384/46688999-0ec9b800-cbff-11e8-93cb-16c8cc417e09.gif)

**Comment by mx0c** [comment]
Should be fixed now. I'm checking the bounce flag in the jump update loop. See line 14 in traits/jump.py. As long as no other entity has the jump trait this should be fine.

**Comment by mx0c** [comment]
As i reworked the jump and movement trait i fixed this issue on the way.
