### ISSUE TITLE
Rework marios jump and left right movement

### ISSUE THREAD

**Issue by mx0c** [mx0c/super-mario-python#30]
Im not satisfied with marios currently movement, any help would be appreciated.

**Comment by astroengisci** [comment]
What specifically aren't you satisfied about?

**Comment by pntbttrvbs** [comment]
@mx0c , I think I see what you're unhappy about. The movement seems a little sluggish. 

go ahead and reopen this, I'm creating a fork to look at this. I think I can add some acceleration and precision to the left/right movement.

**Comment by PhyscoKillerMonkey** [comment]
@mx0c I think another issue with the movement is that you don't have any variation in the jumping. In the real Mario games holding the jump button would give you a larger jump than just tapping it.

I'm going to give this a shot.

**Comment by mx0c** [comment]
Not bad! Maybe adjust the jumpHeight and make the velocity a little faster?

**Comment by PhyscoKillerMonkey** [comment]
@mx0c How exactly do you want the jump height adjusted?

**Comment by PhyscoKillerMonkey** [comment]
@mx0c I've created #38 which makes the jumping very similar to the emulator you linked. Let me know what you think.

**Comment by mx0c** [comment]
Definetly feels better then before. Theres still the issue that when you run down from a platform you can jump mid air. Could you maybe look into this?

**Comment by PhyscoKillerMonkey** [comment]
Fixed jumping when falling, see #40.
