### ISSUE TITLE
Mario can't jumpe while left and up arrows are press together

### ISSUE THREAD

**Issue by szymag** [mx0c/super-mario-python#32]
Other configurations works fine.

**Comment by pntbttrvbs** [comment]
I was able to reproduce the problem, Python 3.6 on Windows 10. Taking a look at this now.

**Comment by PhyscoKillerMonkey** [comment]
@szymag I'm also unable to see this issue. By "left and up" do you mean left and up arrow keys?

**Comment by szymag** [comment]
@PhyscoKillerMonkey, yes I mean left and right arrows. 
@pntbttrvbs, I also used Python 3.6, but on Linux. It means, that here is the problem

**Comment by pntbttrvbs** [comment]
@szymag it looks like the problem is with the keyboard, as stated in the pygame documentation. could you give the new repo a shot? The up button now works as a jump button.

**Comment by szymag** [comment]
` it looks like the problem is with the keyboard, as stated in the pygame documentation`
OK, got it! 
`could you give the new repo a shot?`
@pntbttrvbs, sorry I don't understand what you mean. Can you explain?

**Comment by mx0c** [comment]
You can now also jump with up arrow.
