### ISSUE TITLE
Hidden coins do not add to collected coins

### ISSUE THREAD

**Issue by Sandeep-Ghimire** [mx0c/super-mario-python#44]

**Comment by mx0c** [comment]
what you mean by hidden coins?

**Comment by Sandeep-Ghimire** [comment]
Apologies for not being explicit , I meant coins from boxes which are marked "?"
![screenshot from 2018-10-15 20-19-04](https://user-images.githubusercontent.com/24954470/47020542-4e515080-d179-11e8-8a27-461b5eecfaa1.png)

**Comment by mx0c** [comment]
Oh i see. If you want you can fix it.
