### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Perseus-Perry** [mx0c/super-mario-python#55]

**Comment by ThomasChr** [comment]
My PRs in October where accepted after a few days, so I don‘t think that this repo is dead...

**Comment by Perseus-Perry** [comment]
Well if that's the case them I'm interested in collaborating. It would be a pleasure if someone added me as a contributor.

**Comment by mx0c** [comment]
If you wanna contribute just fork the repo and open pull request's :)

**Comment by Perseus-Perry** [comment]
ah shit . my bad. im fairly new to github and was directly trynna make a new branch without forking.
thanks = )
