### ISSUE TITLE
Koopa shell only kills Mario

### ISSUE THREAD

**Issue by thcheetah777** [mx0c/super-mario-python#62]
When you step on a Koopa character and make it move, it only kills the player when you hit it, but not the other enemies

**Comment by Veguinho** [comment]
I can try to do it! If you assign me I will start working on it

**Comment by Veguinho** [comment]
In which class should the collision be happening?

**Comment by mx0c** [comment]
@Veguinho Sure, you should look into entities/Koopa.py, traits/LeftRightWalkTrait.py & classes/Collider.py.

**Comment by Veguinho** [comment]
Got it! It was farely easy to do. Just added a collider checker inside the Goomba and Koopa classes!
Now I need to add the sound of when they die. Could you open another issue for me to add the sound too? That would help me get some more point for the hacktober fest :)

**Comment by mx0c** [comment]
Great, what you also could do is to make this system more general so if a new enemy type is added to the game you just f.e. inherit from a baseclass.

**Comment by Veguinho** [comment]
Yeah this is a good idea! I'm gonna try doing that too.
