### ISSUE TITLE
Add Sound when koopa shell kills other enemies

### ISSUE THREAD

**Issue by mx0c** [mx0c/super-mario-python#68]
@Veguinho

**Comment by Veguinho** [comment]
Thanks! Will start working on it!
Just a question, in which part of the code are the objects from the Goomba class initilized? This would help me pass the sound object to them, to be accessed inside the Goomba class.

**Comment by mx0c** [comment]
They are initialized in Levels.py (addGoomba(...)) when loading the Level.

**Comment by Veguinho** [comment]
Ok. Will give it a shot!

**Comment by mx0c** [comment]
Thanks ! Could you maybe add those 2 soundfiles: kick.ogg, brick-bump.ogg (from here: https://github.com/meth-meth-method/super-mario/tree/master/public/audio/fx) and play the kick if the shell is kicked and the brick bump when killing enemies.

**Comment by Veguinho** [comment]
Ok sure! Im gonna do that now
