### ISSUE TITLE
Koopas not rendering with transparent background

### ISSUE THREAD

**Issue by mitruly** [mx0c/super-mario-python#84]
**Description**
Koopa sprites are being rendered with a non-transparent background:

<img width="752" alt="koopa_non_transparent" src="https://user-images.githubusercontent.com/12224090/97070225-647e1c80-159c-11eb-9b79-575d2a5c647d.png">

**Acceptance Criteria**
Convert sprites to render with a transparent background.

**Comment by mitruly** [comment]
@mx0c just wondering - was there a reason #83 and #85 were reverted post-merge?

**Comment by mx0c** [comment]
@mitruly yes, look at https://github.com/mx0c/super-mario-python/pull/85
